/**
 * ============================================
 *  TAROT CARD DATA
 * ============================================
 *  所有塔羅牌資料集中管理於此。
 *  如需新增 / 修改牌卡，只需編輯此檔案。
 * ============================================
 */

var TarotData = {
  cards: [
    {
      id: "the-fool",
      name: "THE FOOL",
      number: "0",
      uprightImage: "https://images.plurk.com/5sx9kaPdoyQo2QA3LudLeL.png  ",
      reversedImage: "https://images.plurk.com/30Q6g9MnCEwh7vKs83KKST.png ",
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑀𝑎𝑦 𝑡ℎ𝑒 𝑢𝑛𝑘𝑛𝑜𝑤𝑛 𝑙𝑒𝑎𝑣𝑒 𝑟𝑜𝑜𝑚 𝑓𝑜𝑟 𝑤ℎ𝑜 𝑦𝑜𝑢 𝑎𝑟𝑒.</span>「願茫茫未知，為真我留一席之地。」<br /><br />身後的退路已被濃霧吞沒。你將行囊換到另一側肩膀，循著微弱的燈火，踏入尚未看清的長廊。那時的你單純地相信，只要一直往前走，總會遇見更好的自己。於是，你笑著，將自己毫無保留地交給了未知。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：Yungu烏鴉",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：山羊"
    },
    {
      id: "the-magician",
      name: "THE MAGICIAN",
      number: "I",
      uprightImage: "https://images.plurk.com/6hdjWInOPvFoRzE5tfHz7f.png",
      reversedImage: "assets/tarot/placeholder-reversed.svg", // Fallback until provided
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝐴 𝑚𝑖𝑟𝑎𝑐𝑙𝑒 𝑏𝑒𝑔𝑖𝑛𝑠 𝑤ℎ𝑒𝑟𝑒 𝑡ℎ𝑒 𝑤𝑖𝑡𝑛𝑒𝑠𝑠 𝑓𝑜𝑟𝑔𝑒𝑡𝑠 𝑡𝑜 𝑑𝑜𝑢𝑏𝑡.</span>「當見證者遺忘了懷疑，奇蹟便悄然綻放。」<br /><br />你將空杯高舉過頭，要求他們先說出酒的滋味。當最後一雙質疑的眼眸閉上，杯底終於傳來水聲。從那一刻起，人們相信你能使無成為有。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：流水",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：",
    },
    {
      id: "the-high-priestess",
      name: "THE HIGH PRIESTESS",
      number: "II",
      uprightImage: "https://images.plurk.com/4lrASQ8zFTkeiWrL79XMsa.png",
      reversedImage: "https://images.plurk.com/IAQv73a7MIbosJR7XLwMy.png",
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝐸𝑣𝑒𝑛 𝑤ℎ𝑎𝑡 𝑤𝑎𝑠 𝑛𝑒𝑣𝑒𝑟 𝑤𝑟𝑖𝑡𝑡𝑒𝑛 ℎ𝑎𝑠 𝑏𝑒𝑒𝑛 𝑟𝑒𝑎𝑑.</span>「那些未落筆的空白，皆已盡入眼底。」<br /><br />書室裡杳無人聲，你卻在書頁間，讀見了自己從未寄出的信。兒時的舊屋、遺忘的夢境，連同那次沒有哭出來的痛楚，都被逐字縫入了沉默。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：祁斯弎",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：擬聲詞",
    },
    { 
      id: "the-empress", 
      name: "THE EMPRESS", 
      number: "III", 
      uprightImage: "https://images.plurk.com/YrfAFmAVzDCgcTV8uPK7J.png", 
      reversedImage: "https://images.plurk.com/7DKHbVA6x9ubULEH9AfVYW.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑀𝑎𝑦 𝑠𝑜𝑚𝑒𝑡ℎ𝑖𝑛𝑔 𝑔𝑟𝑜𝑤 𝑏𝑒𝑦𝑜𝑛𝑑 𝑡ℎ𝑒 𝑠ℎ𝑎𝑝𝑒 𝑜𝑓 𝑡ℎ𝑒 𝑔𝑎𝑟𝑑𝑒𝑛𝑒𝑟'𝑠 ℎ𝑎𝑛𝑑.</span>「願草木蔓生，不拘匠人之手。」<br /><br />花園裡，所有的枝條都得到了最細緻的照料，卻也被修剪成了相同的順從弧度。你蹲在濕潤的泥畔，瞥見一株從石縫間野蠻冒出的幼芽；它那未經雕琢的葉片，正倔強地伸向人跡罕至的那一側。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：阿禾",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：水星",
    },
    { 
      id: "the-emperor", 
      name: "THE EMPEROR", 
      number: "IV", 
      uprightImage: "https://images.plurk.com/50oWEFJm8LxMYdjbhK0IPT.png ", 
      reversedImage: "https://images.plurk.com/yukTJ9dIMsx5qQ41cNKzB.png ", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑀𝑎𝑦 𝑡ℎ𝑒 𝑡ℎ𝑟𝑜𝑛𝑒 𝑒𝑛𝑑𝑢𝑟𝑒 𝑤ℎ𝑎𝑡 𝑖𝑡 𝑑𝑒𝑚𝑎𝑛𝑑𝑠 𝑜𝑓 𝑡ℎ𝑜𝑠𝑒 𝑤ℎ𝑜 𝑘𝑛𝑒𝑒𝑙.</span>「願王座，堪承其加諸俯首者之重。」<br /><br />王冠加身以前，你曾許諾一個不必恐懼的國度。如今城牆築得高過了風暴，城裡的每一扇門，都需要你的允許才能推開。你最初為了保護眾人而許下的承諾，已被一字一句，鑿刻成不容任何人僭越的鐵律。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：七葉",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：阿連",
    },
    { 
      id: "the-hierophant", 
      name: "THE HIEROPHANT", 
      number: "V", 
      uprightImage: "https://images.plurk.com/6H216s5Lz0gL66v9xfUNTX.png", 
      reversedImage: "assets/tarot/placeholder-reversed.svg", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑇ℎ𝑒 ℎ𝑦𝑚𝑛 𝑤𝑎𝑠 𝑓𝑙𝑎𝑤𝑙𝑒𝑠𝑠 𝑤ℎ𝑒𝑟𝑒 𝑦𝑜𝑢𝑟 𝑣𝑜𝑖𝑐𝑒 𝑤𝑎𝑠 𝑚𝑖𝑠𝑠𝑖𝑛𝑔.</span>「在你歌聲缺席的空白處，那曲頌歌完美無瑕。」<br /><br />他們將最初的解答奉為教義。<br />你立於聖壇之上，教導眾人如何向未知俯首。當千百張嘴唇終於發出整齊劃一的誦唱，連你也無法分辨——那究竟是神在說話，還是人們只是學會了完美的模仿。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：芥沢",
    },
    { 
      id: "the-lovers", 
      name: "THE LOVERS", 
      number: "VI", 
      uprightImage: "assets/tarot/placeholder-upright.svg", 
      reversedImage: "assets/tarot/placeholder-reversed.svg", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝐶ℎ𝑜𝑜𝑠𝑒 𝑡ℎ𝑒 𝑣𝑜𝑤 𝑦𝑜𝑢 𝑐𝑎𝑛 𝑏𝑒𝑎𝑟 𝑡𝑜 ℎ𝑒𝑎𝑟 𝑎𝑛𝑠𝑤𝑒𝑟𝑒𝑑.</span>「許下誓約前，先確認你承擔得住它的實現。」<br /><br />你將靈魂的誓言託付給另一個人，那是你第一次如此清晰地看見，自己究竟想成為什麼樣的人。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：家家",
    },
    { 
      id: "the-chariot", 
      name: "THE CHARIOT", 
      number: "VII", uprightImage: "assets/tarot/placeholder-upright.svg", 
      reversedImage: "https://images.plurk.com/Tj1aQPIhtBo7R518hQRQx.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑊ℎ𝑜 𝑟𝑒𝑡𝑢𝑟𝑛𝑠 𝑏𝑒𝑛𝑒𝑎𝑡ℎ 𝑡ℎ𝑒 𝑣𝑖𝑐𝑡𝑜𝑟'𝑠 𝑐𝑟𝑜𝑤𝑛?</span>「勝利的王冠之下，歸來的究竟是誰？」<br /><br />雙手勒住兩股分道揚鑣的巨力，你駕著戰車，穿過一扇又一扇高聳的凱旋門，每迎來一次歡呼，車上的行囊便被剝落一分。<br />先是恐懼，接著是憤怒，後來連那個曾刻在心底的名字也被拋在身後。當終點的旗幟終於在風中獵獵作響，你卻再也想不起，自己究竟是為何而出發。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：和平桃子",
    },
    { 
      id: "strength", 
      name: "STRENGTH", 
      number: "VIII", 
      uprightImage: "https://images.plurk.com/27Cd46JgyaSo1hyV6z5Mz2.png ", 
      reversedImage: "assets/tarot/placeholder-reversed.svg", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑀𝑎𝑦 𝑡ℎ𝑒 𝑏𝑒𝑎𝑠𝑡 𝑏𝑒 ℎ𝑒𝑎𝑟𝑑 𝑏𝑒𝑓𝑜𝑟𝑒 𝑖𝑡 𝑖𝑠 𝑡𝑎𝑚𝑒𝑑.</span>「猛獸受羈前，願先聆其聲。」<br /><br />他們說，你胸中的猛獸終於安靜了。<br />唯有在夜深人靜時，你仍能聽見牠利爪抓撓的聲響，你緩緩伸手按住胸口。慢慢地，抓撓停了，只剩下一股細小的顫抖，隔著掌心傳來。你就這樣靜靜守著它，直到連你自己，也終於敢向黑暗承認了害怕。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：Haruka Chen",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：",
    },
    { 
      id: "the-hermit", 
      name: "THE HERMIT", 
      number: "IX", 
      uprightImage: "assets/tarot/placeholder-upright.svg", 
      reversedImage: "https://images.plurk.com/4ET75pKHYgWxa59VzhEeGc.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝐿𝑒𝑡 𝑡ℎ𝑒 𝑙𝑎𝑚𝑝 𝑟𝑒𝑣𝑒𝑎𝑙 𝑡ℎ𝑒 𝑜𝑛𝑒 𝑤ℎ𝑜 ℎ𝑎𝑠 𝑏𝑒𝑒𝑛 𝑐𝑎𝑟𝑟𝑦𝑖𝑛𝑔 𝑖𝑡.</span>「讓亮起的燈火，映出那個始終提著它的人。」<br /><br />起初，你用燈照亮腳下的路。後來，人群朝著光聚攏、跪拜。於是，你默默走得更遠，遠到任由風雪將足跡一層層覆住。在那片純粹的寂靜裡，燈火終於只為你而亮。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：Skiew",
    },
    { 
      id: "wheel-of-fortune", 
      name: "WHEEL OF FORTUNE", 
      number: "X", 
      uprightImage: "assets/tarot/placeholder-upright.svg", 
      reversedImage: "assets/tarot/placeholder-reversed.svg", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑇ℎ𝑒 𝑤ℎ𝑒𝑒𝑙 𝑚𝑎𝑦 𝑡𝑢𝑟𝑛 𝑎𝑔𝑎𝑖𝑛; 𝑡ℎ𝑒 ℎ𝑜𝑢𝑟 𝑤𝑖𝑙𝑙 𝑛𝑜𝑡 𝑟𝑒𝑡𝑢𝑟𝑛.</span>「命運的巨輪或許會再次轉動，但此刻的光陰已成絕響。」<br /><br />命運的齒輪再次轉回原處，連敲響的鐘聲都與記憶中分毫不差。只是座位上熟悉的面孔少了幾位，而腳下的輪盤，仍舊冷酷地轉動著。當掌聲再度如潮水般響起，這一次，你只是靜靜扶著椅背，沒有跟著眾人起身。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：",
    },
    { 
      id: "justice", 
      name: "JUSTICE", 
      number: "XI", 
      uprightImage: "https://images.plurk.com/5XZnZyX3JIE0nEqK9iRLhk.png", 
      reversedImage: "https://images.plurk.com/6u1Sf5TfgUpfkry4h6tGpX.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝐿𝑒𝑡 𝑡ℎ𝑒 𝑣𝑒𝑟𝑑𝑖𝑐𝑡 𝑎𝑛𝑠𝑤𝑒𝑟 𝑡𝑜 𝑡ℎ𝑒 𝑙𝑖𝑓𝑒 𝑖𝑡 𝑛𝑎𝑚𝑒𝑠.</span>「願審判的重量，對得起它所冠名的靈魂。」<br /><br />那些曾讓你夜不能寐的恐懼與過失，被一同擺上天秤。審判的聲音把你的破碎逐一化作冰冷的罪名。<br />你俯身凝視，卻發現那些決定你命運的砝碼上，從沒有刻度，只有「應有的模樣」。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：喫茶",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：悠遊卡",
    },
    { 
      id: "the-hanged-man", 
      name: "THE HANGED MAN", 
      number: "XII", 
      uprightImage: "https://images.plurk.com/5jDUgRs0Nec5uj0oxREf5W.png", 
      reversedImage: "https://images.plurk.com/1YvomrfKvy1mKluaS7PaXQ.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑇ℎ𝑒 𝑤𝑜𝑟𝑙𝑑 𝑡𝑢𝑟𝑛𝑠 𝑠𝑡𝑟𝑎𝑛𝑔𝑒 𝑤ℎ𝑒𝑛 𝑦𝑜𝑢 𝑠𝑡𝑜𝑝 𝑡𝑢𝑟𝑛𝑖𝑛𝑔 𝑤𝑖𝑡ℎ 𝑖𝑡.</span>「當你不再與世界一同旋轉，日常便露出陌生的模樣。」<br /><br />他們將你的身體倒懸，等待著一聲妥協或求饒。你卻第一次看清了——原來，那片慣於仰望的滿天繁星，靜靜流淌在你的腳下。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：月零",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：MIYO",
    },
    { 
      id: "death", 
      name: "DEATH",
      number: "XIII", 
      uprightImage: "https://images.plurk.com/5j6rGu25Ej9ZRv1kLALlHY.png", 
      reversedImage: "assets/tarot/placeholder-reversed.svg", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑊ℎ𝑎𝑡 𝑒𝑛𝑑𝑠 𝑛𝑒𝑒𝑑 𝑛𝑜𝑡 𝑏𝑒 𝑒𝑟𝑎𝑠𝑒𝑑.</span>「迎來終結的事物，無須被抹去存在的痕跡。」<br /><br />席位空了，可杯底還留著一圈未乾的水痕。你靜靜坐在那裡，等到燭火燃盡、夜色轉深，終於伸出手，將那只杯子輕輕翻扣。從此，不再替它添水。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：鴨心",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：",
    },
    { 
      id: "temperance", 
      name: "TEMPERANCE", 
      number: "XIV", 
      uprightImage: "https://images.plurk.com/46gFwj4N48C9pMI1RkB39A.png", 
      reversedImage: "https://images.plurk.com/1Il4PMNcu0JCox87rtn9lK.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑀𝑎𝑦 𝑤ℎ𝑎𝑡 𝑖𝑠 𝑚𝑖𝑛𝑔𝑙𝑒𝑑 𝑘𝑒𝑒𝑝 𝑡ℎ𝑒 𝑚𝑒𝑚𝑜𝑟𝑦 𝑜𝑓 𝑖𝑡𝑠 𝑠𝑜𝑢𝑟𝑐𝑒.</span>「願彼此交融的事物，依然銘記各自的來處。」<br /><br />兩杯之間，水流緩慢地往返。一邊盛著遠道而來的過往，一邊盛著沿途落下的斑駁。你將它們反覆傾注，那交融出的新滋味，難以命名。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：VVN",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：LiKO",
    },
    { 
      id: "the-devil", 
      name: "THE DEVIL", 
      number: "XV", 
      uprightImage: "https://images.plurk.com/4hI2W6Lm2WryVACFpA7NRa.png", 
      reversedImage: "assets/tarot/placeholder-reversed.svg", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑇ℎ𝑒 𝑐ℎ𝑎𝑖𝑛 𝑤𝑎𝑠 𝑚𝑎𝑑𝑒 𝑡𝑜 𝑓𝑖𝑡 𝑡ℎ𝑒 𝑠ℎ𝑎𝑝𝑒 𝑜𝑓 𝑦𝑜𝑢𝑟 𝑙𝑜𝑛𝑔𝑖𝑛𝑔.</span>「鎖鏈依照你渴望的形狀鑄成。」<br /><br />飢餓得到了餵養，孤獨也有了回音，你終於如願以償地過上了自己祈求的生活。只是在每一次的微笑與許諾之前，你的手總會下意識地抬起，去確認頸項上那條早已嵌進血肉裡的鎖鏈，依然緊緊扣著。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：道士Christii",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：阿思",
    },
    { 
      id: "the-tower", 
      name: "THE TOWER", 
      number: "XVI", 
      uprightImage: "https://images.plurk.com/3PBdO5eVZ52ybQB9Ws2Bmd.png", 
      reversedImage: "assets/tarot/placeholder-reversed.svg", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝐴𝑡 𝑙𝑎𝑠𝑡, 𝑡ℎ𝑒 𝑙𝑖𝑔ℎ𝑡𝑛𝑖𝑛𝑔 𝑟𝑒𝑎𝑐ℎ𝑒𝑠 𝑡ℎ𝑒 𝑝𝑎𝑖𝑛𝑡𝑒𝑑 ℎ𝑒𝑎𝑣𝑒𝑛.</span>「終於，閃電觸及了那片虛妄的彩繪天堂。」<br /><br />他們把通往天國的階梯修得太高，高到足以隔絕塵世所有的哭聲。直到雷光呼嘯而至，無情地劈開那片偽造的穹頂。你站在斷壁殘垣中，驚愕地抬起頭，廢墟之外，是完整而遼闊的天空。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：99",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：",
    },
    { 
      id: "the-star", 
      name: "THE STAR", 
      number: "XVII", 
      uprightImage: "assets/tarot/placeholder-upright.svg", 
      reversedImage: "https://images.plurk.com/2nLEokZnkjacMU3z00wzue.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑇ℎ𝑒 𝑠𝑡𝑎𝑟𝑠 𝑎𝑠𝑘 𝑛𝑜𝑡ℎ𝑖𝑛𝑔 𝑜𝑓 𝑡ℎ𝑒 𝑤𝑜𝑢𝑛𝑑𝑒𝑑.</span>「繁星靜謐，無索於負傷之人。」<br /><br />清澈的水流淌過高塔倒塌後的荒蕪，將星辰的倒影碎在殘破的杯底。長夜仍未給出答案，卻容許那些未竟的祈願，在那一片寂靜裡，繼續發光。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：吉祥物",
    },
    { 
      id: "the-moon", 
      name: "THE MOON", 
      number: "XVIII", 
      uprightImage: "https://images.plurk.com/1UwVCjzK39zU7aJ1eYjV8A.png", 
      reversedImage: "https://images.plurk.com/4jNNgA3KNWxRG8EHDg0oQj.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑁𝑜𝑡 𝑒𝑣𝑒𝑟𝑦 𝑣𝑜𝑖𝑐𝑒 𝑡ℎ𝑎𝑡 𝑘𝑛𝑜𝑤𝑠 𝑦𝑜𝑢𝑟 𝑛𝑎𝑚𝑒 𝑘𝑛𝑜𝑤𝑠 𝑦𝑜𝑢𝑟 𝑤𝑎𝑦.</span>「知曉你姓名的聲音，未必懂得你該走的路。」<br /><br />通往出口的路沉在月色裡，粼粼水面浮起一張張熟悉的臉。他們用最溫柔的姿態，替你預演了未來所有的失敗與顛沛，連那份滿是擔憂的安慰語氣，都與記憶中的聲音分毫不差。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：扇貝",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：潞海",
    },
    { 
      id: "the-sun", 
      name: "THE SUN", 
      number: "XIX", 
      uprightImage: "assets/tarot/placeholder-upright.svg", 
      reversedImage: "https://images.plurk.com/7kDoiIMZvfydk2TOM15xHZ.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑀𝑎𝑦 𝑡ℎ𝑒 𝑙𝑖𝑔ℎ𝑡 𝑓𝑖𝑛𝑑 𝑟𝑜𝑜𝑚 𝑓𝑜𝑟 𝑦𝑜𝑢𝑟 𝑠ℎ𝑎𝑑𝑜𝑤.</span>「願這世間的光芒，始終為你的陰影留一席之地。」<br /><br />日輪升起，萬物各自顯形，血肉重新有了溫度，笑聲有了回音，連那些曾被藏在黑夜裡的創傷，也擁有了清晰的影子。你就這樣帶著所有的曾經，以最真實的模樣，站在白晝中央。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：茜貓",
    },
    { id: "judgement", 
      name: "JUDGEMENT", 
      number: "XX", 
      uprightImage: "https://images.plurk.com/3AKARtrdCXdK6EcF5Hy0S9.png", 
      reversedImage: "https://images.plurk.com/5zbjGwQfBLMNcR8fXBPIY5.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑅𝑖𝑠𝑒, 𝑎𝑛𝑑 𝑐𝑙𝑎𝑖𝑚 𝑡ℎ𝑒 𝑙𝑖𝑓𝑒 𝑡ℎ𝑎𝑡 𝑠𝑡𝑖𝑙𝑙 𝑏𝑒𝑎𝑟𝑠 𝑦𝑜𝑢𝑟 𝑛𝑎𝑚𝑒.</span>「起身吧，去認領那始終只屬於你的命運。」<br /><br />號角響起，眾人等候宣讀姓名。你也曾把每一次呼吸留給那道聲音，盼祂告訴你，究竟何時才算足夠。如今，那些被刪去的、畏縮的、失約的、見證過的，與拼命活下來的——都已經站在你的名字之下。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：耐下",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：准野",
    },
    { 
      id: "the-world", 
      name: "THE WORLD", 
      number: "XXI", 
      uprightImage: "https://images.plurk.com/23VedpOG20ID2Z9pYfFLTW.png", 
      reversedImage: "https://images.plurk.com/48UDVCc9AHlxDZKwyWVOtp.png", 
      text: "<span style=\"display: block; margin-bottom: 8px;\">𝑀𝑎𝑦 𝑡ℎ𝑒 𝑐𝑖𝑟𝑐𝑙𝑒 ℎ𝑜𝑙𝑑 𝑎𝑙𝑙 𝑡ℎ𝑎𝑡 𝑦𝑜𝑢 ℎ𝑎𝑣𝑒 𝑏𝑒𝑒𝑛.</span>「願生命的圓，安放你所有的過往。」<br /><br />故事翻至終章，四方的見證者合攏花環，所有的迷惘，都已結成了果實。你翻回過去留下的空白書頁，鄭重寫下自己的名字，並將沿途散落的相遇與告別，悉數安放於行囊。<br /><br />前方的大門再度敞開——這一次，身後的腳步，與你一同前行。",
      uprightAuthor: "── 正位｜Upright ──<br />🎨：李煥",
      reversedAuthor: "── 逆位｜Reversed ──<br />🎨：",
    }
  ]
};
